name: Update CraftMyWebsite documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create ZIP archive
        run: zip -r archive.zip .

      - name: Send archive to API
        id: send_archive
        env:
          API_URL: ${{ secrets.API_URL }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          response=$(curl -X POST ${{ env.API_URL }} \
          -H "${{ env.API_KEY }}" \
          -F "file=@archive.zip" \
          -F "filename=archive.zip")
          echo "$response" > response.json

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Check API response
        run: |
          status=$(cat response.json | jq -r '.status')
          if [ "$status" != "1" ]; then
            echo "Error in API response. Status: $status"
            exit 1
          fi

      - name: Get new schem
        run: curl -X GET 'https://apiv2.craftmywebsite.fr/v1/docs/schem'